export const processes = [
  {
    id: 1,
    arrivalTime: 0,
    burstTime: 5,
    completed: 0,
    color: "#3B82F6",
    startTime: null,
    completionTime: null,
  },
  {
    id: 2,
    arrivalTime: 1,
    burstTime: 4,
    completed: 0,
    color: "#10B981",
    startTime: null,
    completionTime: null,
  },
  {
    id: 3,
    arrivalTime: 3,
    burstTime: 6,
    completed: 0,
    color: "#F59E0B",
    startTime: null,
    completionTime: null,
  },
  {
    id: 4,
    arrivalTime: 0,
    burstTime: 5,
    completed: 0,
    color: "#34D399",
    startTime: null,
    completionTime: null,
  },
];